### ISSUE TITLE
screamlearnn 같이 고쳐줄사람!

### ISSUE THREAD

**Issue by Haydnkr** [6hamuge/OSS_Dudeozy#1]
screamlearnn혼자서 풀기에는 너무 양이 많고 어려워서 도와줄 사람 연락 보내줘!
annaconda에서 모듈 설치가 잘 안돼!
분명히 conda list에는 설치되어있다고 나오는데 말이야..!

**Comment by sssumel** [comment]
pip install를 다시 해보고 실행하는 코드 앞에 python을 붙여봐

**Comment by Haydnkr** [comment]
오..! 된다! 고마워!
